project:
  type: website
  resources:
    - "data/*.csv"
    - "data/*.json"
  output-dir: docs

website:
  title: "MADS Computing"
  author: "Alex Reinhart"
  date: "February 17, 2025"
  chapters:
    - index.qmd
    - part: data-engineering.qmd
      chapters:
        - data-engineering/data-pipeline.qmd
        - data-engineering/database-fundamentals.qmd
        - data-engineering/sql.qmd
        - data-engineering/advanced-sql.qmd
        - data-engineering/sql-code.qmd
        - data-engineering/text-search.qmd
        - data-engineering/cloud.qmd
        - data-engineering/distributed-data.qmd
        - data-engineering/project.qmd
    - references.qmd
  appendices:
    - servers.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: style.css

filters:
  - at: pre-ast
    path: solution-filter.lua
  # - at: post-render
  #   path: extract-exercises.lua