project:
  type: website
  resources:
    - "data/*.csv"
    - "data/*.json"
  output-dir: docs

website:
  title: "MADS Computing"
  author: "Alex Reinhart"
  date: "February 17, 2025"
  chapters:
    - index.qmd
    - part: data-engineering.qmd
      chapters:
        - data-engineering/data-pipeline.qmd
        - data-engineering/database-fundamentals.qmd
        - data-engineering/sql.qmd
        - data-engineering/advanced-sql.qmd
        - data-engineering/sql-code.qmd
        - data-engineering/text-search.qmd
        - data-engineering/cloud.qmd
        - data-engineering/distributed-data.qmd
        - large-scale-data/packaging.qmd
        - data-engineering/project.qmd
    - part: large-scale-data.qmd
      chapters:
        - large-scale-data/spark.qmd
        - large-scale-data/spark-data.qmd
        - large-scale-data/spark-ml.qmd
        - large-scale-data/spark-cloud.qmd
        - large-scale-data/rest-apis.qmd
        - large-scale-data/web-scraping.qmd
        - large-scale-data/project.qmd
    - part: computational-methods.qmd
      chapters:
        - computational-methods/intro-pytorch.qmd
        - computational-methods/intro-neural-nets.qmd
        - computational-methods/fitting-nets.qmd
        - computational-methods/cnns.qmd
        - computational-methods/regularization.qmd
        - computational-methods/rnns.qmd
        - computational-methods/dimension-embedding.qmd
    - references.qmd
  appendices:
    - servers.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: style.css

filters:
  - at: pre-ast
    path: solution-filter.lua
  # - at: post-render
  #   path: extract-exercises.lua